---
redirects:
    /schedule: /meet/schedule
alternate_names:
    - westernwashington
    - washington
    - westernwash
    - westernwa
    - westwa
    - westwash
    - westwashington
    - wwashington
